# Utilise le contrôleur Bluetooth LE logiciel de Zephyr (expérimental) au lieu
# de la SoftDevice Controller de Nordic — test pour contourner
# https://github.com/Seeed-Studio/platform-seeedboards/issues/65
CONFIG_BT_LL_SOFTDEVICE=n
CONFIG_BT_LL_SW_SPLIT=y
